spring:
  application:
    name: authentication
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/global_db}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  redis:
    host: localhost
    port: 6379
  liquibase:
    change-log: classpath://db/changelog/db.changelog-master.xml
    enabled: true
    drop-first: false

  mail:
    host: smtp.yandex.ru
    port: 465
    protocol: smtps
    username: ru.kirill.service@yandex.ru
    password: kfixqwdiisdphnuq

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
    topic: audit
  cloud:
    function:
      definition: auditEventPublisher
    bindings:
      auditEventPublisher-out-0:
        destination: audit

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
    enabled: true

service:
  recovery:
    salt: hdsllLkjhHvKkjhgxgfdGkLGJfyfXFzsSgrT89JCgfDFtfggGyGFgfc
    uri: http://95.174.92.252:9090/change-password/{recoveryLink}


security:
  jwt:
    tokenExpiration: 1h
    secret: B9vPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
    metrics:
      enabled: true
      distribution:
        percentiles-histogram:
          http:
            server:
              requests:
                true
        percentiles:
          http:
            server:
              requests:
                - 0.5
                - 0.9
                - 0.99
server:
  port: 0
app:
  changeEmailHost: http://localhost
  apiPrefix: /api/v1