spring:
  application:
    name: post-service
  datasource:
    url: jdbc:postgresql://localhost:5432/post_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  mandatory-file-encoding: UTF-8

  liquibase:
    change-log: classpath://db/changelog/db.changelog-master.xml
    enabled: true
    drop-first: false

server:
  port: 8082
app:
  apiPrefix: /api/v1
