version: '3'
services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_MULTIPLE_DATABASES="user_db","post_db"
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./pg-init-scripts:/docker-entrypoint-initdb.d

  frontend:
    build:
      context: ../frontend/
    image: skillgroup32/frontend
    ports:
      - "8099:80"
    tty: true
    restart: always
    volumes:
      - ./nginx-config:/etc/nginx/conf.d

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/root/redis
      #- ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=redis
      - REDIS_PORT=6379
      #  - REDIS_DATABASES=16
      - REDIS_DATABASES=1
